
## Quantitative

quantitative | inference
-------------|-------------------
1            | $\mu$
2            | $\rho$, regression

## Categorical

variables | categories | inference
----------|------------|-------------------------------------------------------
1         | 2          | $p$, $\chi^2$ goodness of fit
1         | 3 or more  | $\chi^2$, goodness of fit
2         | 2          | $ p_a - p_0$ $\chi^2$, test for association
2         | 3 or more  | $\chi^2$, test for association

## Quantitative and categorical

categories | inference
-----------|-----------------------
2          | $\mu_0 - \mu_a$, ANOVA
3 or more  | ANOVA

## Regression

response     | inference
-------------|--------------------
quantitative | regression
categorical  | logistic regression

## Pitfalls

### Multiple testing

A Type-I error occurs when the null hypothesis is rejected when it is actually true. The chance that a Type-I error occurs increases as more hypothesis tests are conducted. $100 - 100(1 - \alpha)\%$ of tests will yield statistically significant results by chance.

<!-- Lock5Stat: Ch. 4, p. 290, Example 4.40 -->

* 7129 genes
* 38 patients
* Each patient has one of two types of leukemia
* Each gene was tested for a difference between two types of leukemia

Assume there are no genetic differences between the leukemias. If $\alpha = 0.01$, it can be expected that 1% of the 7129 tests (71 or 72) to yield statistically significant results by chance.

To avoid this pitfall, divide $\alpha$ by the number of tests. E.g., since there are 7129 tests, it can be expected that practically no tests will yield statistically significant results by chance. (_Technically_ 0.01 tests.)

